---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Get latest Auth0 CLI release info.
      uri:
        url: "https://api.github.com/repos/auth0/auth0-cli/releases/latest"
        return_content: yes
      register: auth0_cli_release

    - name: Set Auth0 CLI archive fact.
      set_fact:
        auth0_cli_archive: "auth0-cli_{{ auth0_cli_release.json.tag_name | regex_replace('^v', '') }}_Linux_x86_64.tar.gz"

    - name: Download Auth0 CLI archive.
      get_url:
        url: "https://github.com/auth0/auth0-cli/releases/download/{{ auth0_cli_release.json.tag_name }}/{{ auth0_cli_archive }}"
        dest: "/tmp/{{ auth0_cli_archive }}"
        mode: '0644'

    - name: Extract Auth0 CLI binary.
      unarchive:
        src: "/tmp/{{ auth0_cli_archive }}"
        dest: "/usr/local/bin"
        remote_src: yes

    - name: Ensure Auth0 CLI is executable.
      file:
        path: "/usr/local/bin/auth0"
        mode: '0755'
        state: file

    - name: Remove downloaded archive.
      file:
        path: "/tmp/{{ auth0_cli_archive }}"
        state: absent
