---
- hosts: localhost
  connection: local
  become: true

  vars:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_facts.user_id) }}"
    aws_tools_modules:
      - AWS.Tools.Common
      - AWS.Tools.S3
      - AWS.Tools.RDS
      - AWS.Tools.EC2
      - AWS.Tools.EKS
      - AWS.Tools.ECR
      - AWS.Tools.Glue
      - AWS.Tools.Athena
      - AWS.Tools.Bedrock
      - AWS.Tools.CloudWatch
      - AWS.Tools.CloudWatchLogs
      - AWS.Tools.CostExplorer
      - AWS.Tools.IdentityManagement
      - AWS.Tools.MQ
      - AWS.Tools.MWAA
      - AWS.Tools.Organizations
      - AWS.Tools.SecretsManager
      - AWS.Tools.SecurityToken

  tasks:
    - name: Install AWS.Tools.Installer PowerShell module.
      command: pwsh -Command "Install-Module -Name AWS.Tools.Installer -Force -Scope CurrentUser"
      become_user: "{{ user }}"
      become: yes

    - name: Install AWS.Tools PowerShell modules.
      command: >-
        pwsh -Command "Install-AWSToolsModule
        -Name {{ aws_tools_modules | join(',') }}
        -Force -Confirm:$false -CleanUp -Scope CurrentUser"
      become_user: "{{ user }}"
      become: yes
