- hosts: localhost
  connection: local
  become: yes

  tasks:
    - name: Install command-line utilities and tools
      package:
        name:
          - fzf
          - mc
          - postgresql-client
          - make
          - btop
          - tmux
          - tree
          - ncdu
        state: present
