---
- hosts: localhost
  connection: local
  become: false

  vars:
    home: "{{ ansible_env.HOME }}"

  tasks:
    - name: Install DuckDB CLI.
      shell: "curl -fsSL https://install.duckdb.org | sh"
      args:
        creates: "{{ home }}/.duckdb/cli/latest"
