---
- hosts: localhost
  connection: local
  become: true

  vars:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_user_id) }}"
    home: "/home/{{ user }}"
    nvm_version: "0.40.1"

  tasks:
    - name: Install Node.js.
      package:
        name:
          - nodejs
          - npm
        state: present

    - name: Install nvm.
      become: false
      shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh | bash"
      environment:
        PROFILE: /dev/null
      args:
        creates: "{{ home }}/.nvm/nvm.sh"
