---
- hosts: localhost
  connection: local
  become: true

  vars:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_user_id) }}"
    home: "/home/{{ user }}"

  tasks:
    - name: Install Node.js.
      package:
        name:
          - nodejs
          - npm
        state: present

    - name: Get latest nvm release info.
      uri:
        url: "https://api.github.com/repos/nvm-sh/nvm/releases/latest"
        return_content: yes
      register: nvm_release

    - name: Install nvm.
      become: false
      shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_release.json.tag_name }}/install.sh | bash"
      environment:
        PROFILE: /dev/null
