- hosts: localhost
  connection: local

  vars:
    user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

  tasks:
    - name: Installing apt pipx
      become: true
      package:
        name: pipx
        state: present

    # - name: Self-updating pipx using pipx
    #   community.general.pipx:
    #     executable: ~/.local/bin/pipx
    #     name: pipx
    #     global: true

    - name: Self-updating pipx
      shell: sudo ~/.local/bin/pipx install pipx --global

    - name: Removing apt pipx
      become: yes
      package:
        name: pipx
        state: absent

    - name: Ensuring path
      shell: pipx ensurepath

    - name: Ensuring global path
      become: yes
      shell: ~/.local/bin/pipx install pipx --global

    - name: Installing uv
      community.general.pipx:
        executable: ~/.local/bin/pipx
        name: uv
