---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Get latest sops release info.
      uri:
        url: "https://api.github.com/repos/getsops/sops/releases/latest"
        return_content: yes
      register: sops_release

    - name: Download sops binary.
      get_url:
        url: "https://github.com/getsops/sops/releases/download/{{ sops_release.json.tag_name }}/sops-{{ sops_release.json.tag_name }}.linux.amd64"
        dest: "/usr/local/bin/sops"
        mode: '0755'
        force: yes

    - name: Ensure sops is executable.
      file:
        path: "/usr/local/bin/sops"
        mode: '0755'
        state: file
