---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Map ansible_architecture to telepresence release architecture.
      set_fact:
        telepresence_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

    - name: Download telepresence binary.
      get_url:
        url: "https://app.getambassador.io/download/tel2/linux/{{ telepresence_arch }}/2.7.6/telepresence"
        dest: "/usr/local/bin/telepresence"
        mode: '0755'
        force: yes

    - name: Ensure telepresence is executable.
      file:
        path: "/usr/local/bin/telepresence"
        mode: '0755'
        state: file
