---
- hosts: localhost
  connection: local
  become: true

  vars:
    user: "{{ ansible_facts.env.SUDO_USER | default(ansible_user_id) }}"
    home: "/home/{{ user }}"

  tasks:
    - name: Install uv.
      become: false
      shell: "curl -LsSf https://astral.sh/uv/install.sh | sh"
      args:
        creates: "{{ home }}/.local/bin/uv"
